from __future__ import annotations

from enum import Enum
from typing import TYPE_CHECKING, Generic, Protocol, Self, TypeVar, overload

from .commutative_polynomials import _CommutativePolynomialElement, generate_commutative_variables
from .noncommutative_polynomials import _NonCommutativePolynomialElement, generate_noncommutative_variables

if TYPE_CHECKING:
    from ncpoleon.relaxations import _Constraint

class RewritingStrategy(Enum):
    Greedy = 0

_PolynomialElements = TypeVar("_PolynomialElements", _CommutativePolynomialElement, _NonCommutativePolynomialElement)
_Scalar = TypeVar("_Scalar", float, complex)

# Should be invariant by multiplying and adding within the same vector space
class _VectorSpaceElement(Protocol[_Scalar]):
    def __add__(self, other: _VectorSpaceElement[_Scalar]) -> _VectorSpaceElement[_Scalar]: ...
    def __radd__(self, other: _VectorSpaceElement[_Scalar]) -> _VectorSpaceElement[_Scalar]: ...
    def __mul__(self, other: _Scalar) -> _VectorSpaceElement[_Scalar]: ...
    def __rmul__(self, other: _Scalar) -> _VectorSpaceElement[_Scalar]: ...

# FIXME: change _PolynomialsElements to _MonomialType, that don't accept operators. Maybe do this once hybrid
#  polynomials are done
class _Polynomial(Generic[_PolynomialElements, _Scalar]):
    def change_variables(
        self, mapping: dict[_PolynomialElements, _VectorSpaceElement[_Scalar]]
    ) -> _VectorSpaceElement[_Scalar]: ...
    @overload
    def __add__(self, other: float) -> Self: ...
    @overload
    def __add__(self, other: complex) -> _Polynomial[_PolynomialElements, complex]: ...
    @overload
    def __add__(self, other: _PolynomialElements) -> Self: ...
    @overload
    def __add__(self, other: _Polynomial[_PolynomialElements, float]) -> Self: ...
    @overload
    def __add__(
        self, other: _Polynomial[_PolynomialElements, complex]
    ) -> _Polynomial[_PolynomialElements, complex]: ...
    @overload
    def __radd__(self, other: float) -> Self: ...
    @overload
    def __radd__(self, other: complex) -> _Polynomial[_PolynomialElements, complex]: ...
    @overload
    def __sub__(self, other: float) -> Self: ...
    @overload
    def __sub__(self, other: complex) -> _Polynomial[_PolynomialElements, complex]: ...
    @overload
    def __sub__(self, other: _PolynomialElements) -> Self: ...
    @overload
    def __sub__(self, other: _Polynomial[_PolynomialElements, float]) -> Self: ...
    @overload
    def __sub__(
        self, other: _Polynomial[_PolynomialElements, complex]
    ) -> _Polynomial[_PolynomialElements, complex]: ...
    @overload
    def __rsub__(self, other: float) -> Self: ...
    @overload
    def __rsub__(self, other: complex) -> _Polynomial[_PolynomialElements, complex]: ...
    @overload
    def __mul__(self, other: float) -> Self: ...
    @overload
    def __mul__(self, other: complex) -> _Polynomial[_PolynomialElements, complex]: ...
    @overload
    def __mul__(self, other: _PolynomialElements) -> Self: ...
    @overload
    def __mul__(self, other: _Polynomial[_PolynomialElements, float]) -> Self: ...
    @overload
    def __mul__(
        self, other: _Polynomial[_PolynomialElements, complex]
    ) -> _Polynomial[_PolynomialElements, complex]: ...
    @overload
    def __rmul__(self, other: float) -> Self: ...
    @overload
    def __rmul__(self, other: complex) -> _Polynomial[_PolynomialElements, complex]: ...
    @overload
    def __truediv__(self, other: float) -> Self: ...
    @overload
    def __truediv__(self, other: complex) -> _Polynomial[_PolynomialElements, complex]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __neg__(self) -> Self: ...
    def __pow__(self, power: int) -> Self: ...
    def degree(self) -> int: ...
    def chop(self, delta: float = ...) -> Self: ...
    # Comparison dunders return a Constraint object — overridden as type-checker hint only.
    @overload  # type: ignore[override]
    def __eq__(self, other: float) -> _Constraint[_PolynomialElements, _Scalar]: ...
    @overload
    def __eq__(self, other: complex) -> _Constraint[_PolynomialElements, complex]: ...
    @overload
    def __eq__(self, other: _PolynomialElements) -> _Constraint[_PolynomialElements, _Scalar]: ...
    @overload
    def __eq__(self, other: _Polynomial[_PolynomialElements, _Scalar]) -> _Constraint[_PolynomialElements, _Scalar]: ...
    @overload
    def __eq__(self, other: _Polynomial[_PolynomialElements, complex]) -> _Constraint[_PolynomialElements, complex]: ...
    @overload
    def __ge__(self, other: float) -> _Constraint[_PolynomialElements, _Scalar]: ...
    @overload
    def __ge__(self, other: complex) -> _Constraint[_PolynomialElements, complex]: ...
    @overload
    def __ge__(self, other: _PolynomialElements) -> _Constraint[_PolynomialElements, _Scalar]: ...
    @overload
    def __ge__(self, other: _Polynomial[_PolynomialElements, _Scalar]) -> _Constraint[_PolynomialElements, _Scalar]: ...
    @overload
    def __ge__(self, other: _Polynomial[_PolynomialElements, complex]) -> _Constraint[_PolynomialElements, complex]: ...
    @overload
    def __le__(self, other: float) -> _Constraint[_PolynomialElements, _Scalar]: ...
    @overload
    def __le__(self, other: complex) -> _Constraint[_PolynomialElements, complex]: ...
    @overload
    def __le__(self, other: _PolynomialElements) -> _Constraint[_PolynomialElements, _Scalar]: ...
    @overload
    def __le__(self, other: _Polynomial[_PolynomialElements, _Scalar]) -> _Constraint[_PolynomialElements, _Scalar]: ...
    @overload
    def __le__(self, other: _Polynomial[_PolynomialElements, complex]) -> _Constraint[_PolynomialElements, complex]: ...
    def __hash__(self) -> int: ...

__all__ = [
    "generate_commutative_variables",
    "generate_noncommutative_variables",
    "RewritingStrategy",
]
