from __future__ import annotations

from typing import Any
from collections.abc import Iterable

class Constraint: ...

class Problem:
    def __init__(self, **kwargs: Any) -> None: ...
    def add_constraint(self, constraint: Constraint) -> None: ...
    def add_list_of_constraints(self, constraints: Iterable[Constraint]) -> None: ...
    def set_objective(self, direction: str, expression: Any) -> None: ...
